import { WORDPRESS_API_URL } from '../constants';
import { WP_Page, WP_Post } from './types';

// Helper to handle API responses
async function fetchAPI(endpoint: string) {
    try {
        const headers = { 'Content-Type': 'application/json' };
        const res = await fetch(`${WORDPRESS_API_URL}${endpoint}`, {
            headers,
        });

        if (!res.ok) {
            console.warn(`Failed to fetch API: ${WORDPRESS_API_URL}${endpoint} (${res.status})`);
            return null;
        }

        const json = await res.json();
        return json;
    } catch (error) {
        console.warn(`Error fetching API: ${WORDPRESS_API_URL}${endpoint}`, error);
        return null;
    }
}

// Mock data for build/template purposes
const MOCK_PAGES = [
    { slug: 'sample-page' },
    { slug: 'menu' },
    { slug: 'contact' },
    { slug: 'events' },
];

const MOCK_PAGE_CONTENT: Record<string, WP_Page> = {
    'home': {
        id: 1,
        date: new Date().toISOString(),
        slug: 'home',
        link: '/',
        title: { rendered: 'Welcome to 4 Seasons Wharton' },
        content: { rendered: '<p>Experience the finest dining and catering in Wharton, NJ.</p><img src="https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-4.0.3&auto=format&fit=crop&w=1920&q=80" alt="Mock Extracted Image" data-caption="Mock Caption" />' },
        excerpt: { rendered: '' },
        parent: 0,
    },
    'sample-page': {
        id: 2,
        date: new Date().toISOString(),
        slug: 'sample-page',
        link: '/sample-page',
        title: { rendered: 'Sample Page' },
        content: { rendered: '<p>This is a sample page generated by the template fallback.</p>' },
        excerpt: { rendered: '' },
        parent: 0,
    },
    'menu': {
        id: 3,
        date: new Date().toISOString(),
        slug: 'menu',
        link: '/menu',
        title: { rendered: 'Our Menu' },
        content: { rendered: '<h2>Appetizers</h2><p>Sample menu items...</p><h2>Entrees</h2><p>Delicious main courses...</p>' },
        excerpt: { rendered: '' },
        parent: 0,
    },
    'contact': {
        id: 4,
        date: new Date().toISOString(),
        slug: 'contact',
        link: '/contact',
        title: { rendered: 'Contact Us' },
        content: { rendered: '<p>123 Main St, Wharton, NJ 07885</p><p>Phone: (555) 123-4567</p><p>Email: info@4seasonswharton.com</p>' },
        excerpt: { rendered: '' },
        parent: 0,
    },
    'events': {
        id: 5,
        date: new Date().toISOString(),
        slug: 'events',
        link: '/events',
        title: { rendered: 'Events' },
        content: { rendered: '<p>Host your next event with us!</p>' },
        excerpt: { rendered: '' },
        parent: 0,
    }
};

export async function getAllPagesWithSlugs() {
    const data = await fetchAPI('/wp/v2/pages?_fields=slug');
    if (!data || !Array.isArray(data)) {
        console.log('Using mock pages for build generation');
        return MOCK_PAGES;
    }
    return data;
}

export async function getPageBySlug(slug: string): Promise<WP_Page | null> {
    const pages = await fetchAPI(`?slug=${slug}&_embed`);
    if (pages?.[0]) return pages[0];

    // Fallback to mock
    return MOCK_PAGE_CONTENT[slug] || null;
}

export async function getPosts(): Promise<WP_Post[]> {
    const data = await fetchAPI('/wp/v2/posts?_embed');
    return Array.isArray(data) ? data : [];
}

export async function getPageContent(slug: string) {
    const pages = await fetchAPI(`/wp/v2/pages?slug=${slug}&_embed`);
    if (pages?.[0]) return pages[0];

    // Fallback to mock
    return MOCK_PAGE_CONTENT[slug] || null;
}
